import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { NextPage } from "next";
import { getAllMentions } from "@/services/api/mentions";

const inter = Inter({ subsets: ["latin"] });

type HomeProps = {
  mentions: any;
};

const Home: NextPage<HomeProps> = ({ mentions }) => {
  console.log(mentions);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={inter.className}>Mentions</h1>
      </main>
    </>
  );
};

Home.getInitialProps = async () => {
  const mentions = await getAllMentions();
  return { mentions };
};

export default Home;
