import Head from "next/head";
import Image from "next/image";
import { Quicksand } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { NextPage } from "next";
import { getAllMentions } from "@/services/api/mentions";
import { convertMentionsToViewModel } from "@/utils/utils";
import { MentionCard } from "@/components/MentionCard/MentionCard";

const quicksand = Quicksand({ subsets: ["latin"] });

type HomeProps = {
  mentions: MentionViewModel[];
};

export type MentionViewModel = {
  sourceType: "blogs" | "web" | "forums" | "twitter";
  sourceName: string;
  createdAt: string;
  title: string;
  description: string;
};

const Home: NextPage<HomeProps> = ({ mentions }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image
          src={"/images/mention.png"}
          alt="A woman holding a megaphone surronded by social media icons"
          width={250}
          height={150}
        />
        <h1 className={`${styles.title} ${quicksand.className}`}>Mentions</h1>

        <ul className={styles.grid}>
          {mentions.map((mention, index) => (
            <li key={`mention-${index}`}>
              <MentionCard {...mention} />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

Home.getInitialProps = async () => {
  const mentionsData = await getAllMentions();
  const mentions = convertMentionsToViewModel(mentionsData.mentions);
  return { mentions };
};

export default Home;
